import 'package:flutter/material.dart';

import '../../../../components/footer.dart';
import '../../../../models/expandable_item.dart';

class TermsAndConditionsScreen extends StatefulWidget {
  const TermsAndConditionsScreen({Key? key}) : super(key: key);

  @override
  _TermsAndConditionsScreenState createState() => _TermsAndConditionsScreenState();
}

class _TermsAndConditionsScreenState extends State<TermsAndConditionsScreen> {
  int? _expandedIndex;

  @override
  Widget build(BuildContext context) {
    return Scaffold( persistentFooterButtons: [
      Footer(),
    ],
      appBar: AppBar(
        backgroundColor: Colors.green.shade300,
        title: const Text('Terms and Conditions'),
      ),
      body: ListView.builder(
        itemCount: expandableItems.length,
        itemBuilder: (context, index) {
          return ExpansionTile(
            leading: Text(
              '${index + 1} .',
              style: const TextStyle(
                fontSize: 15,
                fontWeight: FontWeight.bold,
              ),
            ),
            // backgroundColor: Colors.green.shade100,
            title: Text(expandableItems[index].title),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
            onExpansionChanged: (isExpanded) {
              setState(() {
                _expandedIndex = isExpanded ? index : null;
              });
            },
            initiallyExpanded: index == _expandedIndex,
            children: [
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: Text(expandableItems[index].description),
              ),
             const Divider(thickness: 1,)
            ],
          );
        },
      ),
    );
  }
}


final List<ExpandableItem> expandableItems = [
  ExpandableItem(
    title: 'Terms of Use',
    subtitle: 'Subtitle 1',
    description: "1. This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures."
"\n 2. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, as amended, supplemented or replaced from time to time, that require publishing the Privacy Policy and Terms of Use for access or usage of the website, www.Hrtaa.org"
"\n 3. The domain name www.Hrtaa.org (hereinafter referred to as 'Website')is licensed for use by Hrtaa Online Ventures Private Limited, an Indian Company, duly incorporated under the Indian Companies Act, 1956, with its registered office at HD-026, WeWork, K. Raheja Platinum,Sag Baug Road, Off Andheri-Kurla Road, Marol, Andheri East, Mumbai -400059, Maharashtra India. Hrtaa Online Ventures Inc, duly incorporated under General Corporation Law of Delaware is wholly owned subsidiary of Hrtaa Online Ventures Private Limited (hereinafter both collectively referred to as 'Hrtaa')."
"\n 4. Your use of the Website and Services and tools are governed by the following terms and conditions as mentioned herein as applicable to the Website including the applicable policies, which are incorporated herein by way of reference. If you transact on the Website, you shall be subject to the policies that are applicable to the Website for such transaction. By mere use of the Website, you shall be contracting with Hrtaa Online Ventures Private Limited and Hrtaa Online Ventures Inc. and these terms and conditions including the policies constitute your binding obligations, with Hrtaa."
"\n 5. For the purpose of these Terms of Use, wherever the context so requires 'you' or 'User' shall mean any natural or legal person which shall include both Donors / Contributors (as defined hereinbelow) and Campaigner (as defined herein below) as and where applicable and to be understood so) who has agreed to become a member/user of the Website by providing Registration Data while registering on the Website or signing in through an Associated Partner (via the API), as a Registered User using the computer systems (all such Donors / contributors/ and Campaigner shall hereinafter be collectively referred to as “User”). Hrtaa allows all person(s) to surf / explore the Website without registering on the Website. However, Hrtaa does not allow any contributors/donors to make financial contributions or contributions in kind to any of the campaigner with prior registration / signing in. The term \"we\", \"us\", \"our\" shall mean Hrtaa and the term \“you\” and \“your\” referred to herein shall deem to mean the User"
"6. When you use any of the Services provided by us through the Website, including but not limited to, (e.g. Reviews, Comments, Feedback, etc), you will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into these Terms of Use and shall be considered as part and parcel of these Terms of Use. We reserve the right, at our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to you. It is the responsibility of the User to review these Terms of Use periodically for updates / changes. Your continued use of the Website following the posting of changes will mean that You accept and agree to the revisions."
"ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. BY IMPLIEDLY OR EXPRESSLY ACCEPTING THESE TERMS OF USE, YOU ALSO ACCEPT AND AGREE TO BE BOUND BY THE HRTAA PRIVACY POLICY.,"
  ),
  ExpandableItem(
    title: 'Services of Hrtaa',
    subtitle: 'Subtitle 2',
    description: "(i) Hrtaa is a marketing service provider and the Website merely provides platform services which can be utilized by Users (being Donors / Contributors and Campaigner) and persons browsing / visiting the Website to reach a larger base of people, organizations and causes. Hrtaa is only providing a platform for communication and it is agreed that the transactions whether gratuitous or otherwise shall always be bipartite between the Donor / Contributor and the Campaigner."
   " (ii) The Website is a platform that Donors utilize to meet and interact with various Campaigners and the representatives of several non-profit organizations in India. Based on the representations of the campaigns started by such person(s) and/or a cause supported by such Campaigners and Non Profit Organisations in India, Donors enter into transactions for making contributions or sharing information. All information provided about the campaigns, is that which is provided by the respective Campaigner initiating the Campaign and the non- profit organizations in India for which/on behalf of who the campaigns have been started to raise funds. Hrtaa does not influence or control any campaign on the Website, these are managed by the Campaigners themselves. It is not Hrtaa's intention to influence, induce or coerce any Donor into donating to a campaign; these decisions are made solely by the Campaigner and/ or Donor, as the case may be."

"(iii) The Content (defined in Section 10 below) created in relation to campaigns, is either provided to Hrtaa by the Campaigner themselves or is procured and/ or shot and/ or conducted by Hrtaa with the express consent of the Campaigner (and/ or their guardians). In each case the Content is provided to Hrtaa at the free will of the Campaigner. Hrtaa uses the Content solely to promote/ advertise the Campaign. The User acknowledges that Hrtaa is only a marketing service provider and does not verify the bona fides and genuineness of campaigns (including the information forming part of the Content), and Hrtaa cannot and does not verify specific data provided by the Campaigner in relation to a campaign. Therefore, Hrtaa shall not in any manner be responsible or held accountable for any transaction or potential transaction between the Users."

"(iv) Hrtaa has limited control over all campaigns and information listed and / or advertised on the Website or any other platform and/ or Campaign generated information. It is merely an intermediary and does not interfere in the transaction between Donors / Contributors and Campaigner."

"(v) It is hereby clarified that at no time shall Hrtaa hold any right, title or interest over the funds or rewards (except to the extent as stated herein) or have any obligations or liabilities to provide the same to the Donor / contributor. Hrtaa is not responsible for unsatisfactory or delayed performance of the Campaign by the Campaigner."
  ),
  ExpandableItem(
    title: 'Eligibility of the User (as defined here in below)',
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: 'Campaigner',
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: 'Donor',
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: 'User Account and Registration Obligations',
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: 'Communications',
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: 'Platform for Information, Communication and Transaction',
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: 'Charges',
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: 'General Rules for the Use of the Website',
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: 'Contents Posted on Site',
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: 'Linked Websites / APIs/Social Networking Sites',
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: 'Limited License',
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: 'Privacy',
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: 'Disclaimer of Warranties and Liability',
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: 'Financial Transaction Facility - Donors / Contributors',
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: 'Financial Transaction Facility - Campaigner',
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: 'Compliance with Laws:',
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: "Donor's / Contributors arrangement with Issuing Bank:",
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: "Breach",
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: "Indemnity",
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: "Waiver",
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: "Modifications and Alterations",
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: "Intellectual property rights",
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: "Applicable Law & Jurisdiction",
subtitle: 'Subtitle 3',
description:"3"
  ),
  ExpandableItem(
    title: "Dispute Resolution",
subtitle: 'Subtitle 3',
description:"3"
  ),
   ExpandableItem(
    title: "Limitation of Liability",
subtitle: 'Subtitle 3',
description:"3"
  ),
   ExpandableItem(
    title: "Anti-Money Laundering (AML) policy",
subtitle: 'Subtitle 3',
description:"3"
  ),
   ExpandableItem(
    title: "Termination",
subtitle: 'Subtitle 3',
description:"3"
  ),
   ExpandableItem(
    title: "General",
subtitle: 'Subtitle 3',
description:"3"
  ),
   ExpandableItem(
    title: "User disputes",
subtitle: 'Subtitle 3',
description:"3"
  ),
   ExpandableItem(
    title: "Contact Us",
subtitle: 'Subtitle 3',
description:"3"
  ),

// Add more items as needed
];
